<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PortfolioCompany;

class PortfolioCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        PortfolioCompany::truncate();

        $companies = [
            // AI
            ['name'=>'Adept',            'logo'=>'portfolio/logos/adept.png',            'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.adept.ai/'],
            ['name'=>'Anthropic',        'logo'=>'portfolio/logos/anthropic.png',        'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.anthropic.com'],
            ['name'=>'Applied Compute',  'logo'=>'portfolio/logos/applied_compute.svg',  'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://appliedcompute.com/'],
            ['name'=>'AugmentCode',      'logo'=>'portfolio/logos/augmentcode.png',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.augmentcode.com/'],
            ['name'=>'Black Forest Labs', 'logo'=>'portfolio/logos/black_forest_labs.png','category'=>'AI','stage'=>'Seed',  'website_url'=>'https://bfl.ai/'],
            ['name'=>'Cerebras',         'logo'=>'portfolio/logos/cerebras.png',         'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.cerebras.net/'],
            ['name'=>'Character.AI',     'logo'=>'portfolio/logos/character_ai.png',     'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://character.ai/'],
            ['name'=>'Coactive',         'logo'=>'portfolio/logos/coactive.png',         'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.coactive.ai/'],
            ['name'=>'Covariant',        'logo'=>'portfolio/logos/covariant.png',        'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://covariant.ai/'],
            ['name'=>'Decagon',          'logo'=>'portfolio/logos/decagon.png',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://decagon.ai'],
            ['name'=>'Dev Agents',       'logo'=>'portfolio/logos/dev_agents.webp',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://sdsa.ai/'],
            ['name'=>'ElevenLabs',       'logo'=>'portfolio/logos/elevenlabs.png',       'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://elevenlabs.io'],
            ['name'=>'Harvey',           'logo'=>'portfolio/logos/harvey.png',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.harvey.ai/'],
            ['name'=>'HeyGen',           'logo'=>'portfolio/logos/heygen.svg',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.heygen.com/'],
            ['name'=>'Hippocratic AI',   'logo'=>'portfolio/logos/hippocratic_ai.png',   'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.hippocraticai.com/'],
            ['name'=>'Hugging Face',     'logo'=>'portfolio/logos/hugging_face.png',     'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://huggingface.co/'],
            ['name'=>'Kumo.AI',          'logo'=>'portfolio/logos/kumo_ai.png',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://kumo.ai/'],
            ['name'=>'Lightning AI',     'logo'=>'portfolio/logos/lightning_ai.png',     'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://lightning.ai/'],
            ['name'=>'Magical',          'logo'=>'portfolio/logos/magical.png',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.getmagical.com/'],
            ['name'=>'Mercor',           'logo'=>'portfolio/logos/mercor.png',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://mercor.com/'],
            ['name'=>'Mistral',          'logo'=>'portfolio/logos/mistral.png',          'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://mistral.ai/'],
            ['name'=>'Modular',          'logo'=>'portfolio/logos/modular.png',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.modular.com/'],
            ['name'=>'OpenAI',           'logo'=>'portfolio/logos/openai.png',           'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.openai.com'],
            ['name'=>'Reflection',       'logo'=>'portfolio/logos/reflection.png',       'category'=>'AI','stage'=>'Seed',   'website_url'=>null],
            ['name'=>'Sesame',           'logo'=>'portfolio/logos/sesame.png',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.sesame.com/'],
            ['name'=>'Sierra',           'logo'=>'portfolio/logos/sierra.png',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://sierra.ai'],
            ['name'=>'Skild AI',         'logo'=>'portfolio/logos/skild_ai.png',         'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.skild.ai/'],
            ['name'=>'Snorkel AI',       'logo'=>'portfolio/logos/snorkel_ai.png',       'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://snorkel.ai/'],
            ['name'=>'SSI',              'logo'=>'portfolio/logos/ssi.png',              'category'=>'AI','stage'=>'Seed',   'website_url'=>null],
            ['name'=>'Standard AI',      'logo'=>'portfolio/logos/standard_ai.png',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://standard.ai/'],
            ['name'=>'The Bot Company',  'logo'=>'portfolio/logos/the_bot_company.png',  'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.bot.co/'],
            ['name'=>'Together AI',      'logo'=>'portfolio/logos/together_ai.png',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.together.ai/'],
            ['name'=>'Traversal',        'logo'=>'portfolio/logos/traversal.png',        'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://traversal.com/'],
            ['name'=>'World Labs',       'logo'=>'portfolio/logos/world_labs.png',       'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://worldlabs.ai'],
            // Consumer
            ['name'=>'Airbnb',       'logo'=>'portfolio/logos/airbnb.png',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.airbnb.com/'],
            ['name'=>'Captions',     'logo'=>'portfolio/logos/captions.png',    'category'=>'Consumer','stage'=>'Seed',   'website_url'=>'https://www.captions.ai/'],
            ['name'=>'Course Hero',  'logo'=>'portfolio/logos/course_hero.png', 'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.coursehero.com/'],
            ['name'=>'GOAT',         'logo'=>'portfolio/logos/goat.png',        'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.goat.com/'],
            ['name'=>'Hims',         'logo'=>'portfolio/logos/hims.png',        'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.forhims.com/'],
            ['name'=>'Instacart',    'logo'=>'portfolio/logos/instacart.png',   'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.instacart.com/'],
            ['name'=>'Mandolin',     'logo'=>'portfolio/logos/mandolin.png',    'category'=>'Consumer','stage'=>'Seed',   'website_url'=>'https://www.mandolin.com/'],
            ['name'=>'Meta',         'logo'=>'portfolio/logos/meta.png',        'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.meta.com/'],
            ['name'=>'Patreon',      'logo'=>'portfolio/logos/patreon.png',     'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.patreon.com/'],
            ['name'=>'Reddit',       'logo'=>'portfolio/logos/reddit.png',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.reddit.com/'],
            ['name'=>'Snapchat',     'logo'=>'portfolio/logos/snapchat.png',    'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.snapchat.com/'],
            ['name'=>'StockX',       'logo'=>'portfolio/logos/stockx.png',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://stockx.com/'],
            ['name'=>'Twitter',      'logo'=>'portfolio/logos/twitter.png',     'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://twitter.com/'],
            ['name'=>'Twitch',       'logo'=>'portfolio/logos/twitch.png',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.twitch.tv/'],
            ['name'=>'Warby Parker', 'logo'=>'portfolio/logos/warby_parker.png','category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.warbyparker.com/'],
            // Crypto
            ['name'=>'Anchorage Digital', 'logo'=>'portfolio/logos/anchorage_digital.png','category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.anchorage.com/'],
            ['name'=>'Aztec',             'logo'=>'portfolio/logos/aztec.png',            'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://aztec.network/'],
            ['name'=>'Chainalysis',       'logo'=>'portfolio/logos/chainalysis.png',      'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.chainalysis.com/'],
            ['name'=>'Coinbase',          'logo'=>'portfolio/logos/coinbase.png',         'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.coinbase.com/'],
            ['name'=>'Dapper Labs',       'logo'=>'portfolio/logos/dapper_labs.png',      'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.dapperlabs.com/'],
            ['name'=>'Kalshi',            'logo'=>'portfolio/logos/kalshi.png',           'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://kalshi.com/'],
            ['name'=>'OpenSea',           'logo'=>'portfolio/logos/opensea.png',          'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://opensea.io/'],
            ['name'=>'Polymarket',        'logo'=>'portfolio/logos/polymarket.png',       'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://polymarket.com/'],
            ['name'=>'Uniswap',           'logo'=>'portfolio/logos/uniswap.png',          'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://uniswap.org/'],
            ['name'=>'Yuga Labs',         'logo'=>'portfolio/logos/yuga_labs.png',        'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://www.yuga.com/'],
            // Enterprise
            ['name'=>'Airbyte',          'logo'=>'portfolio/logos/airbyte.png',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://airbyte.com/'],
            ['name'=>'Amplitude',        'logo'=>'portfolio/logos/amplitude.png',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://amplitude.com/'],
            ['name'=>'Anduril',          'logo'=>'portfolio/logos/anduril.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.anduril.com'],
            ['name'=>'Apollo.io',        'logo'=>'portfolio/logos/apollo_io.png',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.apollo.io/'],
            ['name'=>'Applied Intuition','logo'=>'portfolio/logos/applied_intuition.png','category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.appliedintuition.com/'],
            ['name'=>'Armada',           'logo'=>'portfolio/logos/armada.png',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.armada.ai/'],
            ['name'=>'Asana',            'logo'=>'portfolio/logos/asana.png',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://asana.com/'],
            ['name'=>'Astranis',         'logo'=>'portfolio/logos/astranis.svg',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.astranis.com/'],
            ['name'=>'Benchling',        'logo'=>'portfolio/logos/benchling.png',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.benchling.com/'],
            ['name'=>'BetterUp',         'logo'=>'portfolio/logos/betterup.png',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.betterup.com/'],
            ['name'=>'Boom',             'logo'=>'portfolio/logos/boom.png',             'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://boomsupersonic.com/'],
            ['name'=>'Bowery',           'logo'=>'portfolio/logos/bowery.png',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://boweryfarming.com/'],
            ['name'=>'Brex',             'logo'=>'portfolio/logos/brex.png',             'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.brex.com/'],
            ['name'=>'Browser Use',      'logo'=>null,                                   'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://browser-use.com/'],
            ['name'=>'Carta',            'logo'=>'portfolio/logos/carta.png',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://carta.com/'],
            ['name'=>'Checkr',           'logo'=>'portfolio/logos/checkr.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://checkr.com/'],
            ['name'=>'Cockroach Labs',   'logo'=>'portfolio/logos/cockroach_labs.png',   'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.cockroachlabs.com/'],
            ['name'=>'Dropbox',          'logo'=>'portfolio/logos/dropbox.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.dropbox.com/'],
            ['name'=>'Drata',            'logo'=>'portfolio/logos/drata.png',            'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://drata.com/'],
            ['name'=>'Elastic',          'logo'=>'portfolio/logos/elastic.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.elastic.co/'],
            ['name'=>'Figma',            'logo'=>'portfolio/logos/figma.png',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.figma.com/'],
            ['name'=>'Flexport',         'logo'=>'portfolio/logos/flexport.png',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.flexport.com/'],
            ['name'=>'Flock Safety',     'logo'=>'portfolio/logos/flock_safety.png',     'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.flocksafety.com/'],
            ['name'=>'GitHub',           'logo'=>'portfolio/logos/github.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://github.com/'],
            ['name'=>'Google',           'logo'=>'portfolio/logos/google.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.google.com/'],
            ['name'=>'Gusto',            'logo'=>'portfolio/logos/gusto.png',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://gusto.com/'],
            ['name'=>'Human Interest',   'logo'=>'portfolio/logos/human_interest.png',   'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://humaninterest.com/'],
            ['name'=>'Ironclad',         'logo'=>'portfolio/logos/ironclad.png',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://ironcladapp.com/'],
            ['name'=>'Lattice',          'logo'=>'portfolio/logos/lattice.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://lattice.com/'],
            ['name'=>'Mercury',          'logo'=>'portfolio/logos/mercury.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://mercury.com/'],
            ['name'=>'Mux',              'logo'=>'portfolio/logos/mux.png',              'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.mux.com/'],
            ['name'=>'Near',             'logo'=>'portfolio/logos/near.png',             'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://near.org/'],
            ['name'=>'Newfront',         'logo'=>'portfolio/logos/newfront.png',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.newfront.com/'],
            ['name'=>'Notion',           'logo'=>'portfolio/logos/notion.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.notion.so/'],
            ['name'=>'Okta',             'logo'=>'portfolio/logos/okta.png',             'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.okta.com/'],
            ['name'=>'PagerDuty',        'logo'=>'portfolio/logos/pagerduty.png',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.pagerduty.com/'],
            ['name'=>'Parallel',         'logo'=>'portfolio/logos/parallel.png',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://parallel.ai/'],
            ['name'=>'Retool',           'logo'=>'portfolio/logos/retool.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://retool.com/'],
            ['name'=>'Rippling',         'logo'=>'portfolio/logos/rippling.png',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.rippling.com/'],
            ['name'=>'Segment',          'logo'=>'portfolio/logos/segment.png',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://segment.com/'],
            ['name'=>'ShipBob',          'logo'=>'portfolio/logos/shipbob.png',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.shipbob.com/'],
            ['name'=>'Slack',            'logo'=>'portfolio/logos/slack.png',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://slack.com/'],
            ['name'=>'Snapdocs',         'logo'=>null,                                   'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.snapdocs.com/'],
            ['name'=>'Square',           'logo'=>'portfolio/logos/square.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://squareup.com/'],
            ['name'=>'Stripe',           'logo'=>'portfolio/logos/stripe.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://stripe.com/'],
            ['name'=>'Tabular',          'logo'=>'portfolio/logos/tabular.png',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://tabular.io/'],
            ['name'=>'Tecton',           'logo'=>'portfolio/logos/tecton.png',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.tecton.ai/'],
            ['name'=>'The Trade Desk',   'logo'=>'portfolio/logos/the_trade_desk.png',   'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.thetradedesk.com/'],
            ['name'=>'Twilio',           'logo'=>'portfolio/logos/twilio.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.twilio.com/'],
            ['name'=>'Vercel',           'logo'=>'portfolio/logos/vercel.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://vercel.com/'],
            ['name'=>'Veriff',           'logo'=>'portfolio/logos/veriff.png',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.veriff.com/'],
            ['name'=>'Zapier',           'logo'=>'portfolio/logos/zapier.png',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://zapier.com/'],
            ['name'=>'Zip',              'logo'=>'portfolio/logos/zip.png',              'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://ziphq.com/'],
            // Fintech
            ['name'=>'Affirm',       'logo'=>'portfolio/logos/affirm.png',       'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.affirm.com/'],
            ['name'=>'Cedar',        'logo'=>'portfolio/logos/cedar.png',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.cedar.com/'],
            ['name'=>'Credit Karma', 'logo'=>'portfolio/logos/credit_karma.png', 'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.creditkarma.com/'],
            ['name'=>'Deel',         'logo'=>'portfolio/logos/deel.png',         'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.deel.com/'],
            ['name'=>'Ethos',        'logo'=>'portfolio/logos/ethos.png',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.ethoslife.com/'],
            ['name'=>'Guideline',    'logo'=>'portfolio/logos/guideline.png',    'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.guideline.com/'],
            ['name'=>'Method',       'logo'=>'portfolio/logos/method.PNG',       'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://methodfi.com/'],
            ['name'=>'Pilot',        'logo'=>'portfolio/logos/pilot.png',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://pilot.com/'],
            ['name'=>'Revolut',      'logo'=>'portfolio/logos/revolut.png',      'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://revolut.com/'],
            ['name'=>'Ribbon',       'logo'=>'portfolio/logos/ribbon.png',       'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.ribbonhealth.com/'],
            ['name'=>'Roofstock',    'logo'=>'portfolio/logos/roofstock.png',    'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.roofstock.com/'],
            ['name'=>'Wise',         'logo'=>'portfolio/logos/wise.png',         'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://wise.com/'],
            // Healthcare
            ['name'=>'Abridge',             'logo'=>'portfolio/logos/abridge.png',            'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.abridge.com/'],
            ['name'=>'Color',               'logo'=>'portfolio/logos/color.png',              'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.color.com/'],
            ['name'=>'Flatiron Health',     'logo'=>'portfolio/logos/flatiron_health.png',    'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://flatiron.com/'],
            ['name'=>'Formation Bio',       'logo'=>'portfolio/logos/formation_bio.png',      'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.formation.bio/'],
            ['name'=>'GRAIL',               'logo'=>'portfolio/logos/grail.png',              'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://grail.com/'],
            ['name'=>'Mammoth Biosciences', 'logo'=>'portfolio/logos/mammoth_biosciences.png','category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://mammoth.bio/'],
            ['name'=>'Oscar',               'logo'=>'portfolio/logos/oscar.png',              'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://www.hioscar.com/'],
            ['name'=>'Pearl Health',        'logo'=>'portfolio/logos/pearl_health.png',       'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://pearlhealth.com/'],
            ['name'=>'Periodic Labs',       'logo'=>'portfolio/logos/periodic_labs.png',      'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://periodic.com/'],
            ['name'=>'Vetcove',             'logo'=>'portfolio/logos/vetcove.png',            'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.vetcove.com/'],
            // Marketplaces
            ['name'=>'DoorDash',  'logo'=>'portfolio/logos/doordash.png',  'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.doordash.com/'],
            ['name'=>'Eventbrite','logo'=>'portfolio/logos/eventbrite.png','category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.eventbrite.com/'],
            ['name'=>'Faire',     'logo'=>'portfolio/logos/faire.png',     'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.faire.com/'],
            ['name'=>'Pinterest', 'logo'=>'portfolio/logos/pinterest.png', 'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.pinterest.com/'],
        ];

        foreach ($companies as $c) {
            PortfolioCompany::create(array_merge($c, ['is_active' => true, 'is_featured' => false]));
        }
    }
}
