<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PortfolioCompany;

class PortfolioCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            // AI
            ['name'=>'Adept',            'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.adept.ai/'],
            ['name'=>'Anthropic',        'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.anthropic.com'],
            ['name'=>'Applied Compute',  'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://appliedcompute.com/'],
            ['name'=>'AugmentCode',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.augmentcode.com/'],
            ['name'=>'Black Forest Labs', 'category'=>'AI','stage'=>'Seed',  'website_url'=>'https://bfl.ai/'],
            ['name'=>'Cerebras',         'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.cerebras.net/'],
            ['name'=>'Character.AI',     'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://character.ai/'],
            ['name'=>'Coactive',         'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.coactive.ai/'],
            ['name'=>'Covariant',        'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://covariant.ai/'],
            ['name'=>'Decagon',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://decagon.ai'],
            ['name'=>'Dev Agents',       'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://sdsa.ai/'],
            ['name'=>'ElevenLabs',       'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://elevenlabs.io'],
            ['name'=>'Harvey',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.harvey.ai/'],
            ['name'=>'HeyGen',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.heygen.com/'],
            ['name'=>'Hippocratic AI',   'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.hippocraticai.com/'],
            ['name'=>'Hugging Face',     'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://huggingface.co/'],
            ['name'=>'Kumo.AI',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://kumo.ai/'],
            ['name'=>'Lightning AI',     'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://lightning.ai/'],
            ['name'=>'Magical',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.getmagical.com/'],
            ['name'=>'Mercor',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://mercor.com/'],
            ['name'=>'Mistral',          'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://mistral.ai/'],
            ['name'=>'Modular',          'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.modular.com/'],
            ['name'=>'OpenAI',           'category'=>'AI','stage'=>'Growth', 'website_url'=>'https://www.openai.com'],
            ['name'=>'Reflection',       'category'=>'AI','stage'=>'Seed',   'website_url'=>null],
            ['name'=>'Sesame',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.sesame.com/'],
            ['name'=>'Sierra',           'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://sierra.ai'],
            ['name'=>'Skild AI',         'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.skild.ai/'],
            ['name'=>'Snorkel AI',       'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://snorkel.ai/'],
            ['name'=>'SSI',              'category'=>'AI','stage'=>'Seed',   'website_url'=>null],
            ['name'=>'Standard AI',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://standard.ai/'],
            ['name'=>'The Bot Company',  'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.bot.co/'],
            ['name'=>'Together AI',      'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://www.together.ai/'],
            ['name'=>'Traversal',        'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://traversal.com/'],
            ['name'=>'World Labs',       'category'=>'AI','stage'=>'Seed',   'website_url'=>'https://worldlabs.ai'],
            // Consumer
            ['name'=>'Airbnb',       'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.airbnb.com/'],
            ['name'=>'Captions',     'category'=>'Consumer','stage'=>'Seed',   'website_url'=>'https://www.captions.ai/'],
            ['name'=>'Course Hero',  'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.coursehero.com/'],
            ['name'=>'GOAT',         'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.goat.com/'],
            ['name'=>'Hims',         'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.forhims.com/'],
            ['name'=>'Instacart',    'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.instacart.com/'],
            ['name'=>'Mandolin',     'category'=>'Consumer','stage'=>'Seed',   'website_url'=>'https://www.mandolin.com/'],
            ['name'=>'Meta',         'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.meta.com/'],
            ['name'=>'Patreon',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.patreon.com/'],
            ['name'=>'Reddit',       'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.reddit.com/'],
            ['name'=>'Snapchat',     'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.snapchat.com/'],
            ['name'=>'StockX',       'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://stockx.com/'],
            ['name'=>'Twitter',      'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://twitter.com/'],
            ['name'=>'Twitch',       'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.twitch.tv/'],
            ['name'=>'Warby Parker', 'category'=>'Consumer','stage'=>'Growth', 'website_url'=>'https://www.warbyparker.com/'],
            // Crypto
            ['name'=>'Anchorage Digital', 'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.anchorage.com/'],
            ['name'=>'Aztec',             'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://aztec.network/'],
            ['name'=>'Chainalysis',       'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.chainalysis.com/'],
            ['name'=>'Coinbase',          'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.coinbase.com/'],
            ['name'=>'Dapper Labs',       'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://www.dapperlabs.com/'],
            ['name'=>'Kalshi',            'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://kalshi.com/'],
            ['name'=>'OpenSea',           'category'=>'Crypto','stage'=>'Growth', 'website_url'=>'https://opensea.io/'],
            ['name'=>'Polymarket',        'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://polymarket.com/'],
            ['name'=>'Uniswap',           'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://uniswap.org/'],
            ['name'=>'Yuga Labs',         'category'=>'Crypto','stage'=>'Seed',   'website_url'=>'https://www.yuga.com/'],
            // Enterprise
            ['name'=>'Airbyte',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://airbyte.com/'],
            ['name'=>'Amplitude',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://amplitude.com/'],
            ['name'=>'Anduril',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.anduril.com'],
            ['name'=>'Apollo.io',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.apollo.io/'],
            ['name'=>'Applied Intuition','category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.appliedintuition.com/'],
            ['name'=>'Armada',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.armada.ai/'],
            ['name'=>'Asana',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://asana.com/'],
            ['name'=>'Astranis',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.astranis.com/'],
            ['name'=>'Benchling',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.benchling.com/'],
            ['name'=>'BetterUp',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.betterup.com/'],
            ['name'=>'Boom',             'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://boomsupersonic.com/'],
            ['name'=>'Bowery',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://boweryfarming.com/'],
            ['name'=>'Brex',             'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.brex.com/'],
            ['name'=>'Browser Use',      'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://browser-use.com/'],
            ['name'=>'Carta',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://carta.com/'],
            ['name'=>'Checkr',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://checkr.com/'],
            ['name'=>'Cockroach Labs',   'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.cockroachlabs.com/'],
            ['name'=>'Dropbox',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.dropbox.com/'],
            ['name'=>'Drata',            'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://drata.com/'],
            ['name'=>'Elastic',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.elastic.co/'],
            ['name'=>'Figma',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.figma.com/'],
            ['name'=>'Flexport',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.flexport.com/'],
            ['name'=>'Flock Safety',     'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.flocksafety.com/'],
            ['name'=>'GitHub',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://github.com/'],
            ['name'=>'Google',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.google.com/'],
            ['name'=>'Gusto',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://gusto.com/'],
            ['name'=>'Human Interest',   'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://humaninterest.com/'],
            ['name'=>'Ironclad',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://ironcladapp.com/'],
            ['name'=>'Lattice',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://lattice.com/'],
            ['name'=>'Mercury',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://mercury.com/'],
            ['name'=>'Mux',              'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.mux.com/'],
            ['name'=>'Near',             'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://near.org/'],
            ['name'=>'Newfront',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.newfront.com/'],
            ['name'=>'Notion',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.notion.so/'],
            ['name'=>'Okta',             'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.okta.com/'],
            ['name'=>'PagerDuty',        'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.pagerduty.com/'],
            ['name'=>'Parallel',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://parallel.ai/'],
            ['name'=>'Retool',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://retool.com/'],
            ['name'=>'Rippling',         'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.rippling.com/'],
            ['name'=>'Segment',          'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://segment.com/'],
            ['name'=>'ShipBob',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.shipbob.com/'],
            ['name'=>'Slack',            'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://slack.com/'],
            ['name'=>'Snapdocs',         'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.snapdocs.com/'],
            ['name'=>'Square',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://squareup.com/'],
            ['name'=>'Stripe',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://stripe.com/'],
            ['name'=>'Tabular',          'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://tabular.io/'],
            ['name'=>'Tecton',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.tecton.ai/'],
            ['name'=>'The Trade Desk',   'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.thetradedesk.com/'],
            ['name'=>'Twilio',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://www.twilio.com/'],
            ['name'=>'Vercel',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://vercel.com/'],
            ['name'=>'Veriff',           'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://www.veriff.com/'],
            ['name'=>'Zapier',           'category'=>'Enterprise','stage'=>'Growth', 'website_url'=>'https://zapier.com/'],
            ['name'=>'Zip',              'category'=>'Enterprise','stage'=>'Seed',   'website_url'=>'https://ziphq.com/'],
            // Fintech
            ['name'=>'Affirm',       'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.affirm.com/'],
            ['name'=>'Cedar',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.cedar.com/'],
            ['name'=>'Credit Karma', 'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.creditkarma.com/'],
            ['name'=>'Deel',         'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://www.deel.com/'],
            ['name'=>'Ethos',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.ethoslife.com/'],
            ['name'=>'Guideline',    'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.guideline.com/'],
            ['name'=>'Method',       'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://methodfi.com/'],
            ['name'=>'Pilot',        'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://pilot.com/'],
            ['name'=>'Revolut',      'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://revolut.com/'],
            ['name'=>'Ribbon',       'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.ribbonhealth.com/'],
            ['name'=>'Roofstock',    'category'=>'Fintech','stage'=>'Seed',   'website_url'=>'https://www.roofstock.com/'],
            ['name'=>'Wise',         'category'=>'Fintech','stage'=>'Growth', 'website_url'=>'https://wise.com/'],
            // Healthcare
            ['name'=>'Abridge',             'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.abridge.com/'],
            ['name'=>'Color',               'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.color.com/'],
            ['name'=>'Flatiron Health',     'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://flatiron.com/'],
            ['name'=>'Formation Bio',       'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.formation.bio/'],
            ['name'=>'GRAIL',               'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://grail.com/'],
            ['name'=>'Mammoth Biosciences', 'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://mammoth.bio/'],
            ['name'=>'Oscar',               'category'=>'Healthcare','stage'=>'Growth', 'website_url'=>'https://www.hioscar.com/'],
            ['name'=>'Pearl Health',        'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://pearlhealth.com/'],
            ['name'=>'Periodic Labs',       'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://periodic.com/'],
            ['name'=>'Vetcove',             'category'=>'Healthcare','stage'=>'Seed',   'website_url'=>'https://www.vetcove.com/'],
            // Marketplaces
            ['name'=>'DoorDash',  'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.doordash.com/'],
            ['name'=>'Eventbrite','category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.eventbrite.com/'],
            ['name'=>'Faire',     'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.faire.com/'],
            ['name'=>'Pinterest', 'category'=>'Marketplaces','stage'=>'Growth', 'website_url'=>'https://www.pinterest.com/'],
        ];

        foreach ($companies as $c) {
            PortfolioCompany::updateOrCreate(
                ['name' => $c['name']],
                array_merge($c, ['is_active' => true, 'is_featured' => false])
            );
        }
    }
}
